apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: default
  name: DevOpsAdmin
rules:
- apiGroups: ["*"] # Do not always use "" because it will add only core api however, every kubernetes object 
                   # comes under a different apiGroup so if you do not know which object comes under which apiGroup, 
                   # then use * to add all of them.
  resources: ["pods", "deployments"]
  verbs: ["get", "watch", "list"]
