apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: DevOps-RB
  namespace: default
subjects:
# You can specify more than one "subject"
- kind: Group # Group, User, OR ServiceAccount
  name: DevOps # "name" of Group, User, OR ServiceAccount is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: Role #this must be Role or ClusterRole
  name: DevOps # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
