apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-sa
  namespace: jenkins

---
apiVersion: v1
kind: Secret
metadata:
 name: jenkins-sa-secret
 namespace: jenkins
 annotations:
   kubernetes.io/service-account.name: jenkins-sa
type: kubernetes.io/service-account-token 

# Kubernetes will automatically generate an API token inside this secret and then assign that token to the service account. 
# By default, if inside pod yaml we dont specify any service account, Kubernetes will mount the "default sa" token of that ns inside pods.
