# weighted round robin canary
# reference: scroll and see roundrobin https://doc.traefik.io/traefik/routing/providers/kubernetes-crd/
apiVersion: traefik.containo.us/v1alpha1
kind: TraefikService
metadata:
  name: canarydeploymentservice
  namespace: default
spec:
  weighted:
    services:
      - name: service-blue
        port: 80
        weight: 1
      - name: service-red
        port: 80
        weight: 1
      - name: service-green
        port: 80
        weight: 1
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: canaryroute
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`20.203.120.160`) # traefik service ip here from traefik namespace
      kind: Rule
      services:
        - name: canarydeploymentservice
          kind: TraefikService
