apiVersion: v1
kind: Service
metadata:
  name: webserver-service
  namespace: default
spec:
  ports:
    - port: 80 # outside pod internally this service will be accessed using 80 port.
      protocol: TCP
      targetPort: 80 # port of containers
  selector:
    name: webserver-pod-label
  type: LoadBalancer
  # publicly exposed outside your cluster + loadbalanced among multiple nodes + pods

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      name: webserver-pod-label
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  template:
    metadata:
      labels:
        name: webserver-pod-label
    spec:
      containers:
        - name: webserver
          image: nginx
          ports:
            - containerPort: 80
