apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: {{ .Values.servicePort }}
      protocol: TCP
      targetPort: {{ .Values.containerPort }}
  selector:
    name: nginx-pod-label
  type: {{.Values.service.type}}
