apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      name: nginx-pod-label
  template:
    metadata:
      labels:
        name: nginx-pod-label
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: azure-disk-volume
              mountPath: "/usr/share/nginx/html"
      volumes:
        - name: azure-disk-volume
          persistentVolumeClaim:
            claimName: dynamic-deployment-pvc
#
# IMPORTANT
# "Disks" are mounted on nodes and same disk cannot be mounted on multiple nodes at the same time
# that is why azure disk does not supports "ReadWriteMany" access mode.

# IMPORTANT
# Since the access mode of this pvc is "ReadWriteOnce" (volume will be mounted only on a specific node and cant be shared), 
# hance all the replicas of deployment will be created on same node. Pods are created on same node
# if it is ReadWriteOnce mode and dynamic provisioning. If it was static disk provisioning the
# pods could schedule on other nodes as well but they cannot run successfully. Only pods on a
# specific node runs successfully and all the pod replicas will share this same pvc and its
# underlying pv.
