apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: nginx
spec:
  maxReplicas: 10
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-blue-deployment
  metrics:
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 50
# do not forget to add memory metrics under resources of the deployment pod template. Otherwise,
# it would not work.

# uncomment memory under resources in blue-deployment.yaml file.
