apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: my-mysql-ha
  namespace:
provisioner: kubernetes.io/azure-disk
# azure disks are used
# Note: do not use any shared storage like azure file share / nfs etc
parameters:
  skuName: Standard_LRS
  kind: Managed
