apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: DevOps-RB
  namespace: default
subjects:
# You can specify more than one "subject"
- kind: Group
  name: DevOps # "name" is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: ClusterRole
  name: DevOpsAdmin # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
