apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
  labels:
    type: nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.16.0.4 # <NFS_INTERNAL/Private_IP>
    path: "/export" # <NFS_EXPORT_FILE_PATH or EXPORTED_DIRECTORY_PATH>
