apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3 # shared file storage between multiple replicas using same pvc.
  selector:
    matchLabels:
      name: nginx-pod-label
  template:
    metadata:
      labels:
        name: nginx-pod-label
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: azure-file-volume
              mountPath: "/usr/share/nginx/html"
      volumes:
        - name: azure-file-volume
          persistentVolumeClaim:
            claimName: pvc-azurefile-dynamic
