# A storage class is used to define how an Azure file share is created. A storage account is
# "automatically" created in the node resource group for use with the storage class to hold the
# Azure file shares. Choose of the following Azure storage redundancy for skuName:

# Standard_LRS - standard locally redundant storage (LRS)
# Standard_GRS - standard geo-redundant storage (GRS)
# Standard_ZRS - standard zone redundant storage (ZRS)
# Standard_RAGRS - standard read-access geo-redundant storage (RA-GRS)
# Premium_LRS - premium locally redundant storage (LRS)
# Premium_ZRS - premium zone redundant storage (ZRS)

# Minimum premium file share is 100GB.

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: my-custom-azurefile
provisioner: file.csi.azure.com
# replace provisioner with "kubernetes.io/azure-file" if aks version is less than 1.21
allowVolumeExpansion: true
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict
  - actimeo=30
parameters:
  skuName: Premium_LRS
