# if you recreate this pod after storing some data in it, and if the pod is scheduled on another node after
# the deletion, the data will be lost because the pod is now created on a different node this time.
apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  volumes:
    - name: host-volume
      persistentVolumeClaim: # this volume is created from host node path using a pvc.
        claimName: pvc-hostpath
  containers:
    - image: busybox
      name: busybox
      command: ["/bin/sh"]
      args: ["-c", "sleep 1200"] # sleep for 20 minutes
      volumeMounts: # hostpath volume that was created above using pvc is mounted here
        - name: host-volume
          mountPath: /mydata
          # once a fresh volume is mounted in a pod, a lost+found directory is created by default in the
          # newly created mounted path.
