apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurefile-static-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  volumeName: azurefile-static-pv # pv name here
  resources:
    requests:
      storage: 5Gi
