apiVersion: v1
kind: Secret
metadata:
  name: secret-demo
type: Opaque
data:
  username: "dGFzaGlrbW9pbgo="
  password: "dGFzaGlrbW9pbgo="
  # ...
  # secret <key> : <"value should be in base64 format otherwise the kubectl apply command will not work>"
  # secret <key> : "<values can be very large strings and can be used for certificates, private keys etc"
# "when we update a secret object data automatically, the pods gets the new data."

# syntax
# kubectl create secret <secret type tls, generic etc> <secret> --from-literal --from-file --cert --key

# examples
# kubectl create secret generic <secret> --from-literal=<secret_key>=<secret_value> --from-literal=<secret_key>=<secret_value>
# it takes secrets from literal

# kubectl create secret generic <secret> --from-file<path to secret file> --from-file<path to secret file>
# it takes secrets from file.
