apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      name: nginx-pod-label
  template:
    metadata:
      labels:
        name: nginx-pod-label
    spec:
      volumes:
        - name: secretvolume # volume name
          # possible volume types secret | configMap | emptyDir | cinder | or any cloud storage
          # see all the volume type here https://kubernetes.io/docs/concepts/storage/volumes/
          secret:
            # means it is a secret type volume, data will come from a secret
            secretName: secret-demo #<secret name here from which the data will come>
            # All the keys in a secret will become a separate file and their values will
            # be stored inside their respective files.
      containers:
        - name: nginx
          image: nginx
          volumeMounts:
            - name: secretvolume # volume name
              mountPath: "/secret" # volume mount path
          ports:
            - containerPort: 80
          env:
            - name: username
              # <key name through which you want to access the secret variable inside your pod without "">
              valueFrom:
                secretKeyRef:
                  name: secret-demo # <name of the secret object here>
                  key: username # <key name inside secret object without "">

            - name: password
              # <key name through which you want to access the secret variable inside your pod without "">
              valueFrom:
                secretKeyRef:
                  name: secret-demo # <name of the secret object here>
                  key: password # <key name inside secret object without "">
            # ...
